#file for compiling
FILES =  src/Iterator.java src/Collection.java src/HashSet.java   src/LinkedList.java src/List.java  src/ArrayList.java src/Queue.java  src/Set.java    src/Main.java 
#G++ compiler
JAVAC = javac

all: $(FILES)	
	$(JAVAC) $(FILES)
